flujo

diff --git a/.github/actions/backend/action.yaml b/.github/actions/backend/action.yaml
--- a/.github/actions/backend/action.yaml
+++ b/.github/actions/backend/action.yaml
@@ -18,5 +18,10 @@ runs:
       shell: bash
       run: |
         VERSION=$(grep -oP '<version>\\K[^<]+' "${{ inputs.path }}" | sed -n '2p')
+        if [ -z "$VERSION" ]; then
+          echo "Error: No se pudo extraer la versión del archivo pom.xml"
+          exit 1
+        fi
         echo "VERSION=$VERSION"
         echo "version=$VERSION" >> $GITHUB_OUTPUT
+
